### ISSUE TITLE
Comment about the definition of "Parameter Space"

### ISSUE THREAD

**Issue by mahsasedaghat** [USNavalResearchLaboratory/turboWAVE#2]
Hi

In my opinion, the definition of "Parameter Space" in https://turbowave.readthedocs.io/en/latest/ref-geometry.html is not clear.

**Comment by dfgordon** [comment]
Hello, I agree there is probably a better way to explain it.  Maybe the following analogy helps.  Say you draw a straight line on a map of the world, going from New York to Tokyo.  On a globe this line is curved.  In TW, parameter space is like the map, and real space is like the globe.  In TW it is actually simpler than the map/globe system, because all we are doing is a change of coordinates, rather than embedding surfaces in a higher space.

At present TW forces you to draw most things in parameter space, which is not ideal, but can often be worked around.  For Cartesian grids there is no issue since the two spaces are the same.

**Comment by mahsasedaghat** [comment]
Thanks. So, for example, a "sphere" in cylindrical parameter space is the set of all points (r, theta, z) satisfying (r-a)^2+(theta-b)^2+(z-c)^2=d^2, which is not a real sphere.

**Comment by dfgordon** [comment]
Yes that is correct.  N.b. the azimuthal angle is supported at the framework level, but not in all modules (we are often interested in axisymmetric systems).  The "true_sphere" region will always be a real sphere.

**Comment by dfgordon** [comment]
Documentation is clarified.
